'use strict';
var yeoman = require('yeoman-generator');
var chalk = require('chalk');
var yosay = require('yosay');

module.exports = yeoman.extend({
  prompting: function () {
    // Have Yeoman greet the user.
    this.log(yosay(
      'Welcome to the Cedrus ' + chalk.red('generator-cedrus-api-lite') + ' generator!'
    ));

    var prompts = [{
      type: 'input',
      name: 'apiName',
      message: 'What would you like to call your API?',
      default: 'Sample API'
    }, {
      type: 'input',
      name: 'apiDescription',
      message: 'Describe your API?',
      default: 'This is sample API being generated by cedrus-api-lite generator'
    }, {
      type: 'input',
      name: 'apiBasePath',
      message: 'Enter base path of your api?',
      default: '/api'
    }, {
      type: 'checkbox',
      name: 'apiConsumes',
      message: 'What media types does this API consume?',
      choices: [
        {
          name: 'JSON',
          value: 'application/json',
          checked: true
        },
        {
          name: 'XML',
          value: 'application/xml',
          disabled: true
        },
        {
          name: 'TEXT XML',
          value: 'text/xml',
          disabled: true
        },
        {
          name: 'TEXT HTML',
          value: 'text/html',
          disabled: true
        }
      ]
    }, {
      type: 'checkbox',
      name: 'apiProduces',
      message: 'What media types does this API produce?',
      choices: [
        {
          name: 'JSON',
          value: 'application/json',
          checked: true
        },
        {
          name: 'XML',
          value: 'application/xml',
          disabled: true
        },
        {
          name: 'TEXT XML',
          value: 'text/xml',
          disabled: true
        },
        {
          name: 'TEXT HTML',
          value: 'text/html',
          disabled: true
        }
      ]
    }, {
      type: 'confirm',
      name: 'versioningEnabled',
      message: 'Would you like to enable versioning?',
      default: false
    }, {
      when: function (response) {
        return response.versioningEnabled;
      },
      type: 'list',
      name: 'versioningLocation',
      message: 'Where would you like to handle versioning?',
      choices: [{
        name: 'URI',
        value: 'uri'
      }, {
        name: 'Custom Header',
        value: 'custom-header'
      }, {
        name: 'Content Type Header',
        value: 'content-type'
      }]
    }, {
      when: function (response) {
        return (response.versioningEnabled && response.versioningLocation === 'custom-header');
      },
      type: 'input',
      name: 'customHeaderName',
      message: 'Please enter name of your custom header?',
      default: 'Version'
    }, {
      when: function (response) {
        return (response.versioningEnabled && response.versioningLocation === 'uri');
      },
      type: 'list',
      name: 'uriOrder',
      message: 'Please choose URI order.',
      choices: [{
        name: '{resource}/{versionNumber}',
        value: 'resourceFirst'
      }, {
        name: '{versionNumber}/{resource}',
        value: 'versionNumberFirst'
      }]
    }, {
      when: function (response) {
        return (response.versioningEnabled && response.versioningLocation === 'content-type');
      },
      type: 'list',
      name: 'contentTypeOrder',
      message: 'Please choose Content-type Header order.',
      choices: [{
        name: 'application/json+{versionNumber}',
        value: 'applicationFirst'
      }, {
        name: '{versionNumber}+application/json',
        value: 'versionNumberFirst'
      }]
    }, {
      when: function (response) {
        return response.versioningEnabled;
      },
      type: 'input',
      name: 'versionNumber',
      message: 'Please enter version number of your api?',
      default: 'v1'
    }];

    return this.prompt(prompts).then(function (props) {
      var versioning = {
        enabled: props.versioningEnabled,
        type: props.versioningLocation
      };
      if (props.versioningEnabled && props.versioningLocation === 'custom-header') {
        versioning.customHeaderName = props.customHeaderName;
      }
      if (props.versioningEnabled && props.versioningLocation === 'uri') {
        versioning.uriOrder = props.uriOrder;
      }
      if (props.versioningEnabled && props.versioningLocation === 'content-type') {
        versioning.contentTypeOrder = props.contentTypeOrder;
      }
      if (props.versioningEnabled) {
        versioning.versionNumber = [props.versionNumber];
      }
      this.config.set({
        apiOverview: {
          apiName: props.apiName,
          apiBasePath: props.apiBasePath,
          apiDescription: props.apiDescription
        }
      });
      this.config.set({
        discover: {
          apiConsumes: props.apiConsumes,
          apiProduces: props.apiProduces
        }
      });
      this.config.set({
        detail: {
          versioning: versioning
        }
      });
      this.composeWith('cedrus-api-lite:data-input');
    }.bind(this));
  }
});
